# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  name: Mordor

trigger:
  branches:
    include:
    - main
  tags:
    include:
    - 'v*.*.*'

variables:
  hosts_qual: "$(clustersIPS)"
  hosts_prod: "$(clustersIPS)"
  packages: "git+https://informatique:rxf4qdzjc5pccj2423ycuedtyma3ughg6e2oepohoc7oilbbjukq@dev.azure.com/Oeilnc/Bilbo/_git/bilbo-packages"

steps:
- script: |
    echo "Branche : $(Build.SourceBranchName)"
    prod_arg=""
    hosts=$(hosts_qual)
    if [[ $(Build.SourceBranchName) != "main" ]]; then prod_arg="--prod"; hosts=$(hosts_prod); fi
    /azp/deploy.sh conda ${prod_arg} --hosts ${hosts} --packages $(packages)
    if [[ $? != 0 ]]; then echo "Erreur rencontrée, arrêt du déploiement..."; exit 1; fi
    /azp/deploy.sh worker ${prod_arg} --hosts ${hosts}
  displayName: "Maj du package sur les environnements Conda"