# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  name: Mordor

trigger:
  branches:
    include:
    - main
  tags:
    include:
    - 'v*.*.*'

variables:
  hosts_qual: "172.20.10.113,172.20.10.112"
  hosts_prod: "172.20.10.113,172.20.10.112,172.20.10.106,172.20.10.109,172.20.9.103,172.20.10.115,172.20.10.100"
  packages: "git+https://clement.niot:3w5ycaxyg5jnil4vsfnlpdpahodsx2xz2elcgezjw5d7ce7ylh7a@dev.azure.com/Oeilnc/Bilbo/_git/bilbo-packages#egg=generate_indicator"

steps:
- script: |
    echo "Branche : $(Build.SourceBranchName)"
    prod_arg=""
    hosts=$(hosts_qual)
    if [[ $(Build.SourceBranchName) != "main" ]]; then prod_arg="--prod"; hosts=$(hosts_prod); fi
    /azp/deploy.sh conda ${prod_arg} --hosts ${hosts} --packages $(packages)
    if [[ $? != 0 ]]; then echo "Erreur rencontrée, arrêt du déploiement..."; exit 1; fi
    /azp/deploy.sh worker ${prod_arg} --hosts ${hosts}
  displayName: "Maj du package sur les environnements Conda"