name: bilbo
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - cachecontrol=0.14.0
  - cachecontrol-with-filecache=0.14.0
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - cleo=2.1.0
  - colorama=0.4.6
  - crashtest=0.4.1
  - cryptography=42.0.8
  - dbus=1.13.6
  - distlib=0.3.8
  - dulwich=0.21.7
  - expat=2.6.2
  - filelock=3.15.3
  - idna=3.7
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - jaraco.classes=3.4.0
  - jeepney=0.8.0
  - keyring=24.3.1
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.80.2
  - libgomp=13.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libsqlite=3.46.0
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - more-itertools=10.3.0
  - msgpack-python=1.0.8
  - ncurses=6.5
  - openssl=3.3.1
  - pcre2=10.44
  - pexpect=4.9.0
  - pip=24.0
  - pkginfo=1.11.1
  - poetry=1.8.3
  - poetry-core=1.9.0
  - poetry-plugin-export=1.8.0
  - ptyprocess=0.7.0
  - pycparser=2.22
  - pyproject_hooks=1.1.0
  - pysocks=1.7.1
  - python=3.11.8
  - python-build=1.2.1
  - python-fastjsonschema=2.20.0
  - python-installer=0.7.0
  - python_abi=3.11
  - rapidfuzz=3.9.3
  - readline=8.2
  - requests-toolbelt=1.0.0
  - secretstorage=3.3.3
  - shellingham=1.5.4
  - tk=8.6.13
  - tomli=2.0.1
  - tomlkit=0.12.5
  - trove-classifiers=2024.5.22
  - virtualenv=20.26.2
  - wheel=0.43.0
  - xz=5.2.6
  - pip:
      - affine==2.4.0
      - appdirs==1.4.4
      - asttokens==2.4.1
      - attrs==23.2.0
      - beautifulsoup4==4.12.3
      - bqplot==0.12.43
      - branca==0.7.2
      - cachetools==5.3.3
      - certifi==2024.2.2
      - click==8.1.7
      - click-plugins==1.1.1
      - cligj==0.7.2
      - cloudpickle==3.0.0
      - colour==0.1.5
      - comm==0.2.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - dask[complete]==2024.2.1
      - dask-geopandas==0.3.1
      - decorator==5.1.1
      - distributed==2024.2.1
      - earthengine-api==0.1.400
      - eerepr==0.0.4
      - executing==2.0.1
      - fiona==1.9.6
      - folium==0.16.0
      - fonttools==4.51.0
      - fsspec==2024.3.1
      - future==1.0.0
      - geemap==0.32.0
      - geoalchemy2==0.14.7
      - geocoder==1.38.1
      - geopandas==0.14.4
      - google-api-core==2.18.0
      - google-api-python-client==2.127.0
      - google-auth==2.29.0
      - google-auth-httplib2==0.2.0
      - google-cloud-core==2.4.1
      - google-cloud-storage==2.16.0
      - google-crc32c==1.5.0
      - google-resumable-media==2.7.0
      - googleapis-common-protos==1.63.0
      - greenlet==3.0.3
      - h3==3.7.7
      - httplib2==0.22.0
      - intake==2.0.5
      - intake-geopandas==0.4.0
      - intake-sql==0.4.0
      - ipyevents==2.0.2
      - ipyfilechooser==0.6.0
      - ipyleaflet==0.19.0
      - ipython==8.24.0
      - ipytree==0.2.2
      - ipywidgets==8.1.2
      - jedi==0.19.1
      - jinja2==3.1.3
      - joblib==1.4.0
      - jupyter-leaflet==0.19.0
      - jupyterlab-widgets==3.0.10
      - kiwisolver==1.4.5
      - libpysal==4.10
      - locket==1.0.0
      - lz4==4.3.3
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - matplotlib-inline==0.1.7
      - numpy==1.26.4
      - packaging==24.0
      - pandas==2.2.2
      - parso==0.8.4
      - partd==1.4.1
      - patsy==0.5.6
      - pillow==10.3.0
      - platformdirs==4.2.1
      - plotly==5.21.0
      - prompt-toolkit==3.0.43
      - proto-plus==1.23.0
      - protobuf==4.25.3
      - psutil==5.9.8
      - psycopg2==2.9.9
      - pure-eval==0.2.2
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pygments==2.17.2
      - pyogrio==0.9.0
      - pyparsing==3.1.2
      - pyperclip==1.8.2
      - pyproj==3.6.1
      - pyshp==2.3.1
      - python-box==7.1.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.1
      - pyyaml==6.0.1
      - rasterio==1.3.10
      - rasterstats==0.19.0
      - ratelim==0.1.6
      - requests==2.31.0
      - rsa==4.9
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - scooby==0.9.2
      - setuptools==69.5.1
      - shapely==2.0.4
      - simplejson==3.19.2
      - six==1.16.0
      - snuggs==1.4.7
      - sortedcontainers==2.4.0
      - soupsieve==2.5
      - sqlalchemy==2.0.29
      - stack-data==0.6.3
      - statsmodels==0.14.2
      - tblib==3.0.0
      - tenacity==8.2.3
      - threadpoolctl==3.4.0
      - tobler==0.11.2
      - toolz==0.12.1
      - tornado==6.4
      - tqdm==4.66.2
      - traitlets==5.14.3
      - traittypes==0.2.1
      - typing-extensions==4.11.0
      - tzdata==2024.1
      - uritemplate==4.1.1
      - urllib3==2.2.1
      - wcwidth==0.2.13
      - widgetsnbextension==4.0.10
      - xyzservices==2024.4.0
      - zict==3.0.0
      - zipp==3.18.1
