[project]
name = "generate_indicator"
version = "0.1.1"
authors = [
  { name="Clément Niot", email="clement.niot@oeil.nc" },
]
description = "Package permettant de générer des indicateurs à partir de différentes sources de données (Google Earth Engine, ...)."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"