adaptingDataframe:
  renameMap: {
    'level':'type_spatial',
    'upper_libelle':'dimension_spatiale',
    'objectid':'id_thematique'
  }
  setAllClasseValue: "Zone cl\xE9 pour la biodiversit\xE9"
  setValue:
    colName: id_indicateur
    value: 32
  toDrop: []
catalogUri: data_reference.yaml
confDb:
  chunksize: 1000
  schema: pression_eau
  strategy: append
  tableName: kba
confDims:
  isin_id_mesure:
  - 3
  isin_id_spatial:
  - ZEE
confRatio:
  indexList:
  - ogc_fid
  - id_spatial
  ratioByIdSpatial:
  - ZEE
  rationalizeBy: values
dataName: kba
indexRef: ogc_fid
indicateur_dissolve_byList: []
keepList:
- kba
nbchuncks: 1
overlayHow: intersection
