adaptingDataframe:
  setValue:
    colName: id_indicateur
    value: 104
catalogUri: data_reference.yaml
confDb:
  chunksize: 1000
  strategy: append
  tableName: faits_nidification
confDims:
  isin_id_mesure:[]
  isin_id_spatial:
  - ZEE
confRatio:
  indexList:
  - OBJECTID
  - id_spatial
  ratioByIdSpatial:
  - ZEE
  rationalizeBy: values
dataName: observation_nidification
indexRef: OBJECTID
indicateur_dissolve_byList: []
keepList:
- type_espece
- observation
limit: 0
nbchuncks: 100
offset: -1
overlayHow: identity
